# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created: Tue May 14 16:11:32 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_win_main(object):
    def setupUi(self, win_main):
        win_main.setObjectName(_fromUtf8("win_main"))
        win_main.resize(680, 622)
        self.centralwidget = QtGui.QWidget(win_main)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblTitleIcon = QtGui.QLabel(self.centralwidget)
        self.lblTitleIcon.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblTitleIcon.setText(_fromUtf8(""))
        self.lblTitleIcon.setPixmap(QtGui.QPixmap(_fromUtf8("icons/krfb.png")))
        self.lblTitleIcon.setObjectName(_fromUtf8("lblTitleIcon"))
        self.horizontalLayout_2.addWidget(self.lblTitleIcon)
        self.lblTitle = QtGui.QLabel(self.centralwidget)
        self.lblTitle.setStyleSheet(_fromUtf8("font: 75 24pt \"Calibri\";"))
        self.lblTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTitle.setObjectName(_fromUtf8("lblTitle"))
        self.horizontalLayout_2.addWidget(self.lblTitle)
        spacerItem = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnMenuData = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenuData.sizePolicy().hasHeightForWidth())
        self.btnMenuData.setSizePolicy(sizePolicy)
        self.btnMenuData.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/preferences-system-network.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMenuData.setIcon(icon)
        self.btnMenuData.setIconSize(QtCore.QSize(32, 32))
        self.btnMenuData.setCheckable(False)
        self.btnMenuData.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnMenuData.setAutoRaise(True)
        self.btnMenuData.setObjectName(_fromUtf8("btnMenuData"))
        self.horizontalLayout_2.addWidget(self.btnMenuData)
        self.btnMenuExperiment = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenuExperiment.sizePolicy().hasHeightForWidth())
        self.btnMenuExperiment.setSizePolicy(sizePolicy)
        self.btnMenuExperiment.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/applications-science.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMenuExperiment.setIcon(icon1)
        self.btnMenuExperiment.setIconSize(QtCore.QSize(32, 32))
        self.btnMenuExperiment.setCheckable(False)
        self.btnMenuExperiment.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnMenuExperiment.setAutoRaise(True)
        self.btnMenuExperiment.setObjectName(_fromUtf8("btnMenuExperiment"))
        self.horizontalLayout_2.addWidget(self.btnMenuExperiment)
        self.btnMenuOutput = QtGui.QToolButton(self.centralwidget)
        self.btnMenuOutput.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenuOutput.sizePolicy().hasHeightForWidth())
        self.btnMenuOutput.setSizePolicy(sizePolicy)
        self.btnMenuOutput.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/gnumeric.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMenuOutput.setIcon(icon2)
        self.btnMenuOutput.setIconSize(QtCore.QSize(32, 32))
        self.btnMenuOutput.setCheckable(False)
        self.btnMenuOutput.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnMenuOutput.setAutoRaise(True)
        self.btnMenuOutput.setObjectName(_fromUtf8("btnMenuOutput"))
        self.horizontalLayout_2.addWidget(self.btnMenuOutput)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.stack = QtGui.QStackedWidget(self.centralwidget)
        self.stack.setAutoFillBackground(False)
        self.stack.setInputMethodHints(QtCore.Qt.ImhNone)
        self.stack.setFrameShape(QtGui.QFrame.NoFrame)
        self.stack.setFrameShadow(QtGui.QFrame.Raised)
        self.stack.setObjectName(_fromUtf8("stack"))
        self.stackLicense = QtGui.QWidget()
        self.stackLicense.setObjectName(_fromUtf8("stackLicense"))
        self.gridLayout_3 = QtGui.QGridLayout(self.stackLicense)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.textBrowser = QtGui.QTextBrowser(self.stackLicense)
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setFrameShape(QtGui.QFrame.Box)
        self.textBrowser.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser.setSource(QtCore.QUrl(_fromUtf8("file:///X:/Users_Public/Scott/Software/Projects/Telem-A-Gator v4.5/src/changelog.html")))
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout_3.addWidget(self.textBrowser, 3, 0, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_36 = QtGui.QLabel(self.stackLicense)
        self.label_36.setStyleSheet(_fromUtf8("font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);"))
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_18.addWidget(self.label_36)
        self.label_38 = QtGui.QLabel(self.stackLicense)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setMinimumSize(QtCore.QSize(112, 0))
        self.label_38.setText(_fromUtf8(""))
        self.label_38.setPixmap(QtGui.QPixmap(_fromUtf8("icons/up.png")))
        self.label_38.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_18.addWidget(self.label_38)
        self.gridLayout_3.addLayout(self.horizontalLayout_18, 0, 0, 1, 1)
        self.stack.addWidget(self.stackLicense)
        self.stackData = QtGui.QWidget()
        self.stackData.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackData.setAutoFillBackground(False)
        self.stackData.setObjectName(_fromUtf8("stackData"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.stackData)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.stackData)
        self.plainTextEdit.setStyleSheet(_fromUtf8("background-color:transparent;\n"
"\n"
"font: italic 12pt \"Calibri\";\n"
"color: rgb(00,33,66);"))
        self.plainTextEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.plainTextEdit.setFrameShadow(QtGui.QFrame.Sunken)
        self.plainTextEdit.setBackgroundVisible(False)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.groupBox_5 = QtGui.QGroupBox(self.stackData)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self._2 = QtGui.QVBoxLayout(self.groupBox_5)
        self._2.setSpacing(5)
        self._2.setContentsMargins(5, 0, 5, 5)
        self._2.setObjectName(_fromUtf8("_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineInputFolder = QtGui.QLineEdit(self.groupBox_5)
        self.lineInputFolder.setMinimumSize(QtCore.QSize(70, 0))
        self.lineInputFolder.setReadOnly(True)
        self.lineInputFolder.setObjectName(_fromUtf8("lineInputFolder"))
        self.horizontalLayout.addWidget(self.lineInputFolder)
        self.btnSetRaw = QtGui.QToolButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetRaw.sizePolicy().hasHeightForWidth())
        self.btnSetRaw.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/network.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSetRaw.setIcon(icon3)
        self.btnSetRaw.setIconSize(QtCore.QSize(22, 22))
        self.btnSetRaw.setCheckable(False)
        self.btnSetRaw.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnSetRaw.setAutoRaise(False)
        self.btnSetRaw.setObjectName(_fromUtf8("btnSetRaw"))
        self.horizontalLayout.addWidget(self.btnSetRaw)
        self._2.addLayout(self.horizontalLayout)
        self.lblInputLine1 = QtGui.QLabel(self.groupBox_5)
        self.lblInputLine1.setStyleSheet(_fromUtf8("color: rgb(150, 150, 150);"))
        self.lblInputLine1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblInputLine1.setObjectName(_fromUtf8("lblInputLine1"))
        self._2.addWidget(self.lblInputLine1)
        self.lblInputLine2 = QtGui.QLabel(self.groupBox_5)
        self.lblInputLine2.setStyleSheet(_fromUtf8("color: rgb(150, 150, 150);"))
        self.lblInputLine2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblInputLine2.setObjectName(_fromUtf8("lblInputLine2"))
        self._2.addWidget(self.lblInputLine2)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_7 = QtGui.QGroupBox(self.stackData)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self._4 = QtGui.QVBoxLayout(self.groupBox_7)
        self._4.setSpacing(5)
        self._4.setContentsMargins(5, 0, 5, 5)
        self._4.setObjectName(_fromUtf8("_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineLocation = QtGui.QLineEdit(self.groupBox_7)
        self.lineLocation.setMinimumSize(QtCore.QSize(70, 0))
        self.lineLocation.setReadOnly(True)
        self.lineLocation.setObjectName(_fromUtf8("lineLocation"))
        self.horizontalLayout_4.addWidget(self.lineLocation)
        self.btnSetLocation = QtGui.QToolButton(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetLocation.sizePolicy().hasHeightForWidth())
        self.btnSetLocation.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/gnome-fs-home.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSetLocation.setIcon(icon4)
        self.btnSetLocation.setIconSize(QtCore.QSize(22, 22))
        self.btnSetLocation.setCheckable(False)
        self.btnSetLocation.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnSetLocation.setAutoRaise(False)
        self.btnSetLocation.setObjectName(_fromUtf8("btnSetLocation"))
        self.horizontalLayout_4.addWidget(self.btnSetLocation)
        self._4.addLayout(self.horizontalLayout_4)
        self.lblOutputLine1 = QtGui.QLabel(self.groupBox_7)
        self.lblOutputLine1.setStyleSheet(_fromUtf8("color: rgb(150, 150, 150);"))
        self.lblOutputLine1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblOutputLine1.setObjectName(_fromUtf8("lblOutputLine1"))
        self._4.addWidget(self.lblOutputLine1)
        self.lblOutputLine2 = QtGui.QLabel(self.groupBox_7)
        self.lblOutputLine2.setStyleSheet(_fromUtf8("color: rgb(150, 150, 150);"))
        self.lblOutputLine2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblOutputLine2.setObjectName(_fromUtf8("lblOutputLine2"))
        self._4.addWidget(self.lblOutputLine2)
        self.lblOutputLine3 = QtGui.QLabel(self.groupBox_7)
        self.lblOutputLine3.setStyleSheet(_fromUtf8("color: rgb(150, 150, 150);"))
        self.lblOutputLine3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblOutputLine3.setObjectName(_fromUtf8("lblOutputLine3"))
        self._4.addWidget(self.lblOutputLine3)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.grpConvert = QtGui.QGroupBox(self.stackData)
        self.grpConvert.setObjectName(_fromUtf8("grpConvert"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.grpConvert)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setContentsMargins(6, 0, 6, 6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnConvert = QtGui.QToolButton(self.grpConvert)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnConvert.sizePolicy().hasHeightForWidth())
        self.btnConvert.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("icons/software-update-urgent.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnConvert.setIcon(icon5)
        self.btnConvert.setIconSize(QtCore.QSize(32, 32))
        self.btnConvert.setCheckable(False)
        self.btnConvert.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnConvert.setAutoRaise(True)
        self.btnConvert.setArrowType(QtCore.Qt.NoArrow)
        self.btnConvert.setObjectName(_fromUtf8("btnConvert"))
        self.horizontalLayout_5.addWidget(self.btnConvert)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(20, -1, 0, -1)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.progConvertAnimal = QtGui.QProgressBar(self.grpConvert)
        self.progConvertAnimal.setEnabled(False)
        self.progConvertAnimal.setMaximum(0)
        self.progConvertAnimal.setProperty("value", -1)
        self.progConvertAnimal.setInvertedAppearance(False)
        self.progConvertAnimal.setObjectName(_fromUtf8("progConvertAnimal"))
        self.gridLayout.addWidget(self.progConvertAnimal, 1, 0, 1, 1)
        self.progConvertFeature = QtGui.QProgressBar(self.grpConvert)
        self.progConvertFeature.setEnabled(False)
        self.progConvertFeature.setMaximum(0)
        self.progConvertFeature.setProperty("value", -1)
        self.progConvertFeature.setObjectName(_fromUtf8("progConvertFeature"))
        self.gridLayout.addWidget(self.progConvertFeature, 1, 1, 1, 1)
        self.lblConvertFeature = QtGui.QLabel(self.grpConvert)
        self.lblConvertFeature.setEnabled(False)
        self.lblConvertFeature.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblConvertFeature.setObjectName(_fromUtf8("lblConvertFeature"))
        self.gridLayout.addWidget(self.lblConvertFeature, 0, 1, 1, 1)
        self.lblConvertAnimal = QtGui.QLabel(self.grpConvert)
        self.lblConvertAnimal.setEnabled(False)
        self.lblConvertAnimal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblConvertAnimal.setObjectName(_fromUtf8("lblConvertAnimal"))
        self.gridLayout.addWidget(self.lblConvertAnimal, 0, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.grpConvert)
        self.stack.addWidget(self.stackData)
        self.stackExperiment = QtGui.QWidget()
        self.stackExperiment.setObjectName(_fromUtf8("stackExperiment"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.stackExperiment)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(5, -1, -1, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.stackExperiment)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.stackExperiment)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.listAnimals = QtGui.QListWidget(self.stackExperiment)
        self.listAnimals.setFrameShape(QtGui.QFrame.Box)
        self.listAnimals.setFrameShadow(QtGui.QFrame.Sunken)
        self.listAnimals.setLineWidth(1)
        self.listAnimals.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listAnimals.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listAnimals.setSelectionRectVisible(True)
        self.listAnimals.setObjectName(_fromUtf8("listAnimals"))
        self.gridLayout_2.addWidget(self.listAnimals, 1, 0, 1, 1)
        self.listFeatures = QtGui.QListWidget(self.stackExperiment)
        self.listFeatures.setFrameShape(QtGui.QFrame.Box)
        self.listFeatures.setFrameShadow(QtGui.QFrame.Sunken)
        self.listFeatures.setLineWidth(1)
        self.listFeatures.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listFeatures.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listFeatures.setSelectionRectVisible(True)
        self.listFeatures.setObjectName(_fromUtf8("listFeatures"))
        self.gridLayout_2.addWidget(self.listFeatures, 1, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.stackExperiment)
        self.label_28.setStyleSheet(_fromUtf8("color: rgb(150, 150, 150);"))
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 3, 0, 1, 1)
        self.lblLastData = QtGui.QLabel(self.stackExperiment)
        self.lblLastData.setStyleSheet(_fromUtf8("color: rgb(150, 150, 150);"))
        self.lblLastData.setObjectName(_fromUtf8("lblLastData"))
        self.gridLayout_2.addWidget(self.lblLastData, 4, 1, 1, 1)
        self.lblFirstData = QtGui.QLabel(self.stackExperiment)
        self.lblFirstData.setStyleSheet(_fromUtf8("color: rgb(150, 150, 150);"))
        self.lblFirstData.setObjectName(_fromUtf8("lblFirstData"))
        self.gridLayout_2.addWidget(self.lblFirstData, 3, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.stackExperiment)
        self.label_29.setStyleSheet(_fromUtf8("color: rgb(150, 150, 150);"))
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 4, 0, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_11 = QtGui.QGroupBox(self.stackExperiment)
        self.groupBox_11.setCheckable(False)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setMargin(5)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_7 = QtGui.QLabel(self.groupBox_11)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_10.addWidget(self.label_7)
        self.lineBinsize = QtGui.QLineEdit(self.groupBox_11)
        self.lineBinsize.setObjectName(_fromUtf8("lineBinsize"))
        self.horizontalLayout_10.addWidget(self.lineBinsize)
        self.cmbBinsize = QtGui.QComboBox(self.groupBox_11)
        self.cmbBinsize.setObjectName(_fromUtf8("cmbBinsize"))
        self.horizontalLayout_10.addWidget(self.cmbBinsize)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.chkSweeps = QtGui.QCheckBox(self.groupBox_11)
        self.chkSweeps.setObjectName(_fromUtf8("chkSweeps"))
        self.verticalLayout_9.addWidget(self.chkSweeps)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_23 = QtGui.QLabel(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_11.addWidget(self.label_23)
        self.cmbVariance = QtGui.QComboBox(self.groupBox_11)
        self.cmbVariance.setObjectName(_fromUtf8("cmbVariance"))
        self.horizontalLayout_11.addWidget(self.cmbVariance)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5.addWidget(self.groupBox_11)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.grpBaseline = QtGui.QGroupBox(self.stackExperiment)
        self.grpBaseline.setCheckable(True)
        self.grpBaseline.setObjectName(_fromUtf8("grpBaseline"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.grpBaseline)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setContentsMargins(5, 0, 5, 5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setSpacing(5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_34 = QtGui.QLabel(self.grpBaseline)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_6.addWidget(self.label_34, 4, 0, 1, 1)
        self.lineBaseStartTime = QtGui.QLineEdit(self.grpBaseline)
        self.lineBaseStartTime.setMinimumSize(QtCore.QSize(70, 0))
        self.lineBaseStartTime.setObjectName(_fromUtf8("lineBaseStartTime"))
        self.gridLayout_6.addWidget(self.lineBaseStartTime, 2, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.grpBaseline)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1)
        self.lineBaseStartDate = QtGui.QLineEdit(self.grpBaseline)
        self.lineBaseStartDate.setMinimumSize(QtCore.QSize(60, 0))
        self.lineBaseStartDate.setObjectName(_fromUtf8("lineBaseStartDate"))
        self.gridLayout_6.addWidget(self.lineBaseStartDate, 2, 1, 1, 1)
        self.lineBaseEndDate = QtGui.QLineEdit(self.grpBaseline)
        self.lineBaseEndDate.setMinimumSize(QtCore.QSize(60, 0))
        self.lineBaseEndDate.setObjectName(_fromUtf8("lineBaseEndDate"))
        self.gridLayout_6.addWidget(self.lineBaseEndDate, 4, 1, 1, 1)
        self.lineBaseEndTime = QtGui.QLineEdit(self.grpBaseline)
        self.lineBaseEndTime.setMinimumSize(QtCore.QSize(70, 0))
        self.lineBaseEndTime.setObjectName(_fromUtf8("lineBaseEndTime"))
        self.gridLayout_6.addWidget(self.lineBaseEndTime, 4, 2, 1, 1)
        self.label_32 = QtGui.QLabel(self.grpBaseline)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setStyleSheet(_fromUtf8("color: rgb(150, 150, 150);"))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_6.addWidget(self.label_32, 1, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.grpBaseline)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setStyleSheet(_fromUtf8("color: rgb(150, 150, 150);"))
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_6.addWidget(self.label_33, 1, 2, 1, 1)
        self.btnSetTime4 = QtGui.QToolButton(self.grpBaseline)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetTime4.sizePolicy().hasHeightForWidth())
        self.btnSetTime4.setSizePolicy(sizePolicy)
        self.btnSetTime4.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("icons/gtk-media-previous-rtl.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSetTime4.setIcon(icon6)
        self.btnSetTime4.setIconSize(QtCore.QSize(16, 16))
        self.btnSetTime4.setCheckable(False)
        self.btnSetTime4.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnSetTime4.setAutoRaise(True)
        self.btnSetTime4.setObjectName(_fromUtf8("btnSetTime4"))
        self.gridLayout_6.addWidget(self.btnSetTime4, 4, 3, 1, 1)
        self.btnSetTime3 = QtGui.QToolButton(self.grpBaseline)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetTime3.sizePolicy().hasHeightForWidth())
        self.btnSetTime3.setSizePolicy(sizePolicy)
        self.btnSetTime3.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("icons/stock_media-prev.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSetTime3.setIcon(icon7)
        self.btnSetTime3.setIconSize(QtCore.QSize(16, 16))
        self.btnSetTime3.setCheckable(False)
        self.btnSetTime3.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnSetTime3.setAutoRaise(True)
        self.btnSetTime3.setObjectName(_fromUtf8("btnSetTime3"))
        self.gridLayout_6.addWidget(self.btnSetTime3, 2, 3, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(8)
        self.horizontalLayout_7.setContentsMargins(5, -1, 0, -1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_31 = QtGui.QLabel(self.grpBaseline)
        self.label_31.setEnabled(False)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_7.addWidget(self.label_31)
        self.lineBaseTitle = QtGui.QLineEdit(self.grpBaseline)
        self.lineBaseTitle.setEnabled(False)
        self.lineBaseTitle.setMinimumSize(QtCore.QSize(70, 0))
        self.lineBaseTitle.setFrame(False)
        self.lineBaseTitle.setObjectName(_fromUtf8("lineBaseTitle"))
        self.horizontalLayout_7.addWidget(self.lineBaseTitle)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5.addWidget(self.grpBaseline)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.groupBox_12 = QtGui.QGroupBox(self.stackExperiment)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setContentsMargins(5, 0, 5, 5)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setSpacing(5)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_39 = QtGui.QLabel(self.groupBox_12)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_8.addWidget(self.label_39, 4, 0, 1, 1)
        self.lineExpEndDate = QtGui.QLineEdit(self.groupBox_12)
        self.lineExpEndDate.setMinimumSize(QtCore.QSize(60, 0))
        self.lineExpEndDate.setObjectName(_fromUtf8("lineExpEndDate"))
        self.gridLayout_8.addWidget(self.lineExpEndDate, 4, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_8.addWidget(self.label_19, 2, 0, 1, 1)
        self.lineExpStartDate = QtGui.QLineEdit(self.groupBox_12)
        self.lineExpStartDate.setMinimumSize(QtCore.QSize(60, 0))
        self.lineExpStartDate.setObjectName(_fromUtf8("lineExpStartDate"))
        self.gridLayout_8.addWidget(self.lineExpStartDate, 2, 1, 1, 1)
        self.lineExpStartTime = QtGui.QLineEdit(self.groupBox_12)
        self.lineExpStartTime.setMinimumSize(QtCore.QSize(70, 0))
        self.lineExpStartTime.setObjectName(_fromUtf8("lineExpStartTime"))
        self.gridLayout_8.addWidget(self.lineExpStartTime, 2, 2, 1, 1)
        self.lineExpEndTime = QtGui.QLineEdit(self.groupBox_12)
        self.lineExpEndTime.setMinimumSize(QtCore.QSize(70, 0))
        self.lineExpEndTime.setObjectName(_fromUtf8("lineExpEndTime"))
        self.gridLayout_8.addWidget(self.lineExpEndTime, 4, 2, 1, 1)
        self.btnSetTime1 = QtGui.QToolButton(self.groupBox_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetTime1.sizePolicy().hasHeightForWidth())
        self.btnSetTime1.setSizePolicy(sizePolicy)
        self.btnSetTime1.setText(_fromUtf8(""))
        self.btnSetTime1.setIcon(icon7)
        self.btnSetTime1.setIconSize(QtCore.QSize(16, 16))
        self.btnSetTime1.setCheckable(False)
        self.btnSetTime1.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnSetTime1.setAutoRaise(True)
        self.btnSetTime1.setObjectName(_fromUtf8("btnSetTime1"))
        self.gridLayout_8.addWidget(self.btnSetTime1, 2, 3, 1, 1)
        self.label_41 = QtGui.QLabel(self.groupBox_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setStyleSheet(_fromUtf8("color: rgb(150, 150, 150);"))
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_8.addWidget(self.label_41, 1, 2, 1, 1)
        self.label_40 = QtGui.QLabel(self.groupBox_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setStyleSheet(_fromUtf8("color: rgb(150, 150, 150);"))
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_8.addWidget(self.label_40, 1, 1, 1, 1)
        self.btnSetTime2 = QtGui.QToolButton(self.groupBox_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetTime2.sizePolicy().hasHeightForWidth())
        self.btnSetTime2.setSizePolicy(sizePolicy)
        self.btnSetTime2.setText(_fromUtf8(""))
        self.btnSetTime2.setIcon(icon6)
        self.btnSetTime2.setIconSize(QtCore.QSize(16, 16))
        self.btnSetTime2.setCheckable(False)
        self.btnSetTime2.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnSetTime2.setAutoRaise(True)
        self.btnSetTime2.setObjectName(_fromUtf8("btnSetTime2"))
        self.gridLayout_8.addWidget(self.btnSetTime2, 4, 3, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(8)
        self.horizontalLayout_9.setContentsMargins(5, -1, 0, -1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_42 = QtGui.QLabel(self.groupBox_12)
        self.label_42.setEnabled(False)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.horizontalLayout_9.addWidget(self.label_42)
        self.lineExpTitle = QtGui.QLineEdit(self.groupBox_12)
        self.lineExpTitle.setEnabled(False)
        self.lineExpTitle.setMinimumSize(QtCore.QSize(70, 0))
        self.lineExpTitle.setFrame(False)
        self.lineExpTitle.setObjectName(_fromUtf8("lineExpTitle"))
        self.horizontalLayout_9.addWidget(self.lineExpTitle)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.verticalLayout_5.addWidget(self.groupBox_12)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.btnSummary = QtGui.QToolButton(self.stackExperiment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSummary.sizePolicy().hasHeightForWidth())
        self.btnSummary.setSizePolicy(sizePolicy)
        self.btnSummary.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnSummary.setAutoFillBackground(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("icons/spreadsheet.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSummary.setIcon(icon8)
        self.btnSummary.setIconSize(QtCore.QSize(32, 32))
        self.btnSummary.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnSummary.setArrowType(QtCore.Qt.NoArrow)
        self.btnSummary.setObjectName(_fromUtf8("btnSummary"))
        self.verticalLayout_5.addWidget(self.btnSummary)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.stack.addWidget(self.stackExperiment)
        self.stackOutput = QtGui.QWidget()
        self.stackOutput.setObjectName(_fromUtf8("stackOutput"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.stackOutput)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.groupBox_8 = QtGui.QGroupBox(self.stackOutput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_14.setSpacing(5)
        self.horizontalLayout_14.setContentsMargins(5, 0, 5, 5)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.btnExecute = QtGui.QToolButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExecute.sizePolicy().hasHeightForWidth())
        self.btnExecute.setSizePolicy(sizePolicy)
        self.btnExecute.setIcon(icon5)
        self.btnExecute.setIconSize(QtCore.QSize(32, 32))
        self.btnExecute.setCheckable(False)
        self.btnExecute.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnExecute.setAutoRaise(True)
        self.btnExecute.setObjectName(_fromUtf8("btnExecute"))
        self.horizontalLayout_14.addWidget(self.btnExecute)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.progExecute = QtGui.QProgressBar(self.groupBox_8)
        self.progExecute.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progExecute.sizePolicy().hasHeightForWidth())
        self.progExecute.setSizePolicy(sizePolicy)
        self.progExecute.setMinimum(0)
        self.progExecute.setMaximum(1)
        self.progExecute.setProperty("value", -1)
        self.progExecute.setTextVisible(True)
        self.progExecute.setObjectName(_fromUtf8("progExecute"))
        self.verticalLayout_11.addWidget(self.progExecute)
        self.lblStatus = QtGui.QLabel(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStatus.sizePolicy().hasHeightForWidth())
        self.lblStatus.setSizePolicy(sizePolicy)
        self.lblStatus.setStyleSheet(_fromUtf8("color: rgb(150, 150, 150);"))
        self.lblStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblStatus.setObjectName(_fromUtf8("lblStatus"))
        self.verticalLayout_11.addWidget(self.lblStatus)
        self.horizontalLayout_14.addLayout(self.verticalLayout_11)
        self.verticalLayout_10.addWidget(self.groupBox_8)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.groupBox_9 = QtGui.QGroupBox(self.stackOutput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_15.setSpacing(5)
        self.horizontalLayout_15.setContentsMargins(5, 0, 5, 5)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.chkPlotBaseline = QtGui.QCheckBox(self.groupBox_9)
        self.chkPlotBaseline.setStyleSheet(_fromUtf8("background-color: rgb(187, 202, 255);"))
        self.chkPlotBaseline.setObjectName(_fromUtf8("chkPlotBaseline"))
        self.horizontalLayout_15.addWidget(self.chkPlotBaseline)
        self.chkPlotExperiment = QtGui.QCheckBox(self.groupBox_9)
        self.chkPlotExperiment.setStyleSheet(_fromUtf8("background-color: rgb(158, 234, 189);"))
        self.chkPlotExperiment.setObjectName(_fromUtf8("chkPlotExperiment"))
        self.horizontalLayout_15.addWidget(self.chkPlotExperiment)
        self.chkPlotNormalized = QtGui.QCheckBox(self.groupBox_9)
        self.chkPlotNormalized.setStyleSheet(_fromUtf8("background-color: rgb(255, 206, 206);"))
        self.chkPlotNormalized.setObjectName(_fromUtf8("chkPlotNormalized"))
        self.horizontalLayout_15.addWidget(self.chkPlotNormalized)
        self.horizontalLayout_16.addWidget(self.groupBox_9)
        self.groupBox_10 = QtGui.QGroupBox(self.stackOutput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_17.setSpacing(5)
        self.horizontalLayout_17.setContentsMargins(5, 0, 5, 5)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.chkPrimary = QtGui.QCheckBox(self.groupBox_10)
        self.chkPrimary.setObjectName(_fromUtf8("chkPrimary"))
        self.horizontalLayout_17.addWidget(self.chkPrimary)
        self.chkSecondary = QtGui.QCheckBox(self.groupBox_10)
        self.chkSecondary.setObjectName(_fromUtf8("chkSecondary"))
        self.horizontalLayout_17.addWidget(self.chkSecondary)
        self.chkErr = QtGui.QCheckBox(self.groupBox_10)
        self.chkErr.setObjectName(_fromUtf8("chkErr"))
        self.horizontalLayout_17.addWidget(self.chkErr)
        self.horizontalLayout_16.addWidget(self.groupBox_10)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.grpOutput = QtGui.QGroupBox(self.stackOutput)
        self.grpOutput.setObjectName(_fromUtf8("grpOutput"))
        self._5 = QtGui.QVBoxLayout(self.grpOutput)
        self._5.setSpacing(5)
        self._5.setContentsMargins(10, 0, 5, 5)
        self._5.setObjectName(_fromUtf8("_5"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_21 = QtGui.QLabel(self.grpOutput)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_12.addWidget(self.label_21)
        self.lineOutputFolder = QtGui.QLineEdit(self.grpOutput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineOutputFolder.sizePolicy().hasHeightForWidth())
        self.lineOutputFolder.setSizePolicy(sizePolicy)
        self.lineOutputFolder.setMinimumSize(QtCore.QSize(70, 0))
        self.lineOutputFolder.setReadOnly(True)
        self.lineOutputFolder.setObjectName(_fromUtf8("lineOutputFolder"))
        self.horizontalLayout_12.addWidget(self.lineOutputFolder)
        self.btnSetOutputFolder = QtGui.QToolButton(self.grpOutput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetOutputFolder.sizePolicy().hasHeightForWidth())
        self.btnSetOutputFolder.setSizePolicy(sizePolicy)
        self.btnSetOutputFolder.setIcon(icon3)
        self.btnSetOutputFolder.setIconSize(QtCore.QSize(22, 22))
        self.btnSetOutputFolder.setCheckable(False)
        self.btnSetOutputFolder.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnSetOutputFolder.setAutoRaise(False)
        self.btnSetOutputFolder.setObjectName(_fromUtf8("btnSetOutputFolder"))
        self.horizontalLayout_12.addWidget(self.btnSetOutputFolder)
        self.btnOutputOpen = QtGui.QToolButton(self.grpOutput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOutputOpen.sizePolicy().hasHeightForWidth())
        self.btnOutputOpen.setSizePolicy(sizePolicy)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("icons/view-calendar-list.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOutputOpen.setIcon(icon9)
        self.btnOutputOpen.setIconSize(QtCore.QSize(22, 22))
        self.btnOutputOpen.setCheckable(False)
        self.btnOutputOpen.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnOutputOpen.setAutoRaise(False)
        self.btnOutputOpen.setObjectName(_fromUtf8("btnOutputOpen"))
        self.horizontalLayout_12.addWidget(self.btnOutputOpen)
        self._5.addLayout(self.horizontalLayout_12)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setContentsMargins(5, 0, 5, 0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.btnExcel = QtGui.QToolButton(self.grpOutput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExcel.sizePolicy().hasHeightForWidth())
        self.btnExcel.setSizePolicy(sizePolicy)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("icons/application-vnd.ms-excel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExcel.setIcon(icon10)
        self.btnExcel.setIconSize(QtCore.QSize(32, 32))
        self.btnExcel.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnExcel.setObjectName(_fromUtf8("btnExcel"))
        self.gridLayout_5.addWidget(self.btnExcel, 2, 1, 1, 1)
        self.btnImages = QtGui.QToolButton(self.grpOutput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnImages.sizePolicy().hasHeightForWidth())
        self.btnImages.setSizePolicy(sizePolicy)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("icons/gnome-mime-application-vnd.stardivision.impress.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnImages.setIcon(icon11)
        self.btnImages.setIconSize(QtCore.QSize(32, 32))
        self.btnImages.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnImages.setObjectName(_fromUtf8("btnImages"))
        self.gridLayout_5.addWidget(self.btnImages, 2, 0, 1, 1)
        self.btnHTML = QtGui.QToolButton(self.grpOutput)
        self.btnHTML.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHTML.sizePolicy().hasHeightForWidth())
        self.btnHTML.setSizePolicy(sizePolicy)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("icons/wordprocessing.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHTML.setIcon(icon12)
        self.btnHTML.setIconSize(QtCore.QSize(32, 32))
        self.btnHTML.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnHTML.setObjectName(_fromUtf8("btnHTML"))
        self.gridLayout_5.addWidget(self.btnHTML, 2, 2, 1, 1)
        self.btnSaveScheme = QtGui.QToolButton(self.grpOutput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSaveScheme.sizePolicy().hasHeightForWidth())
        self.btnSaveScheme.setSizePolicy(sizePolicy)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("icons/text-x-changelog.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveScheme.setIcon(icon13)
        self.btnSaveScheme.setIconSize(QtCore.QSize(32, 32))
        self.btnSaveScheme.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnSaveScheme.setObjectName(_fromUtf8("btnSaveScheme"))
        self.gridLayout_5.addWidget(self.btnSaveScheme, 2, 3, 1, 1)
        self._5.addLayout(self.gridLayout_5)
        self.verticalLayout_10.addWidget(self.grpOutput)
        self.framePreview = QtGui.QFrame(self.stackOutput)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.framePreview.setPalette(palette)
        self.framePreview.setAutoFillBackground(True)
        self.framePreview.setFrameShape(QtGui.QFrame.Box)
        self.framePreview.setFrameShadow(QtGui.QFrame.Raised)
        self.framePreview.setLineWidth(1)
        self.framePreview.setObjectName(_fromUtf8("framePreview"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.framePreview)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setMargin(1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setMargin(6)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_22 = QtGui.QLabel(self.framePreview)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_8.addWidget(self.label_22)
        self.cmbFeature = QtGui.QComboBox(self.framePreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFeature.sizePolicy().hasHeightForWidth())
        self.cmbFeature.setSizePolicy(sizePolicy)
        self.cmbFeature.setObjectName(_fromUtf8("cmbFeature"))
        self.horizontalLayout_8.addWidget(self.cmbFeature)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.lblPlotTitle = QtGui.QLabel(self.framePreview)
        self.lblPlotTitle.setStyleSheet(_fromUtf8("font: 12pt \"Calibri\";"))
        self.lblPlotTitle.setText(_fromUtf8(""))
        self.lblPlotTitle.setObjectName(_fromUtf8("lblPlotTitle"))
        self.horizontalLayout_8.addWidget(self.lblPlotTitle)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.btnLaunchInteractive = QtGui.QToolButton(self.framePreview)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("icons/launcher-program.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLaunchInteractive.setIcon(icon14)
        self.btnLaunchInteractive.setIconSize(QtCore.QSize(16, 16))
        self.btnLaunchInteractive.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnLaunchInteractive.setObjectName(_fromUtf8("btnLaunchInteractive"))
        self.horizontalLayout_8.addWidget(self.btnLaunchInteractive)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.mplwidget = MatplotlibWidget(self.framePreview)
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.verticalLayout_4.addWidget(self.mplwidget)
        self.verticalLayout_10.addWidget(self.framePreview)
        self.stack.addWidget(self.stackOutput)
        self.stackAbout = QtGui.QWidget()
        self.stackAbout.setObjectName(_fromUtf8("stackAbout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.stackAbout)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.textEdit = QtGui.QTextEdit(self.stackAbout)
        self.textEdit.setEnabled(False)
        self.textEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.stack.addWidget(self.stackAbout)
        self.stackKey = QtGui.QWidget()
        self.stackKey.setObjectName(_fromUtf8("stackKey"))
        self.gridLayout_4 = QtGui.QGridLayout(self.stackKey)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 0, 0, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.stackKey)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_4.addWidget(self.lineEdit_3, 2, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self.stackKey)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_4.addWidget(self.label_27, 2, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.stackKey)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_4.addWidget(self.label_26, 1, 1, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.stackKey)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_4.addWidget(self.lineEdit_2, 1, 2, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.stackKey)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_4.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.stackKey)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_4.addWidget(self.label_25, 0, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 0, 3, 1, 1)
        self.stack.addWidget(self.stackKey)
        self.stackExport = QtGui.QWidget()
        self.stackExport.setObjectName(_fromUtf8("stackExport"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.stackExport)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_24 = QtGui.QLabel(self.stackExport)
        self.label_24.setStyleSheet(_fromUtf8("font: 75 12pt \"MS Shell Dlg 2\";"))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_7.addWidget(self.label_24)
        self.label_20 = QtGui.QLabel(self.stackExport)
        self.label_20.setText(_fromUtf8(""))
        self.label_20.setPixmap(QtGui.QPixmap(_fromUtf8("images/exportSettings2.jpg")))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_7.addWidget(self.label_20)
        self.stack.addWidget(self.stackExport)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.textDebug = QtGui.QPlainTextEdit(self.page)
        self.textDebug.setStyleSheet(_fromUtf8("font: 8pt \"OCR A Extended\";"))
        self.textDebug.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textDebug.setReadOnly(True)
        self.textDebug.setBackgroundVisible(False)
        self.textDebug.setObjectName(_fromUtf8("textDebug"))
        self.verticalLayout_3.addWidget(self.textDebug)
        self.stack.addWidget(self.page)
        self.verticalLayout.addWidget(self.stack)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(6, 0, 6, 6)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.lblDebug = QtGui.QLabel(self.centralwidget)
        self.lblDebug.setEnabled(False)
        self.lblDebug.setObjectName(_fromUtf8("lblDebug"))
        self.horizontalLayout_13.addWidget(self.lblDebug)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        win_main.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(win_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAdvanced = QtGui.QMenu(self.menubar)
        self.menuAdvanced.setObjectName(_fromUtf8("menuAdvanced"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuVIEW = QtGui.QMenu(self.menubar)
        self.menuVIEW.setObjectName(_fromUtf8("menuVIEW"))
        win_main.setMenuBar(self.menubar)
        self.actionScheme_Editor = QtGui.QAction(win_main)
        self.actionScheme_Editor.setCheckable(True)
        self.actionScheme_Editor.setChecked(True)
        self.actionScheme_Editor.setObjectName(_fromUtf8("actionScheme_Editor"))
        self.actionData_Analysis = QtGui.QAction(win_main)
        self.actionData_Analysis.setCheckable(True)
        self.actionData_Analysis.setChecked(True)
        self.actionData_Analysis.setObjectName(_fromUtf8("actionData_Analysis"))
        self.actionDebug_Log = QtGui.QAction(win_main)
        self.actionDebug_Log.setObjectName(_fromUtf8("actionDebug_Log"))
        self.actionEdit_Scheme = QtGui.QAction(win_main)
        self.actionEdit_Scheme.setEnabled(False)
        self.actionEdit_Scheme.setObjectName(_fromUtf8("actionEdit_Scheme"))
        self.actionGenerate_Command = QtGui.QAction(win_main)
        self.actionGenerate_Command.setEnabled(False)
        self.actionGenerate_Command.setObjectName(_fromUtf8("actionGenerate_Command"))
        self.actionPop_up_Log = QtGui.QAction(win_main)
        self.actionPop_up_Log.setObjectName(_fromUtf8("actionPop_up_Log"))
        self.actionLog_Settings = QtGui.QAction(win_main)
        self.actionLog_Settings.setEnabled(False)
        self.actionLog_Settings.setObjectName(_fromUtf8("actionLog_Settings"))
        self.actionLog_to_file = QtGui.QAction(win_main)
        self.actionLog_to_file.setCheckable(True)
        self.actionLog_to_file.setChecked(True)
        self.actionLog_to_file.setEnabled(False)
        self.actionLog_to_file.setObjectName(_fromUtf8("actionLog_to_file"))
        self.actionExportFormat = QtGui.QAction(win_main)
        self.actionExportFormat.setObjectName(_fromUtf8("actionExportFormat"))
        self.actionDocumentation_2 = QtGui.QAction(win_main)
        self.actionDocumentation_2.setEnabled(False)
        self.actionDocumentation_2.setObjectName(_fromUtf8("actionDocumentation_2"))
        self.actionAbout = QtGui.QAction(win_main)
        self.actionAbout.setEnabled(True)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSet_raw_txt_path = QtGui.QAction(win_main)
        self.actionSet_raw_txt_path.setObjectName(_fromUtf8("actionSet_raw_txt_path"))
        self.actionSet_data_npy_path = QtGui.QAction(win_main)
        self.actionSet_data_npy_path.setObjectName(_fromUtf8("actionSet_data_npy_path"))
        self.actionSet_output_folder = QtGui.QAction(win_main)
        self.actionSet_output_folder.setObjectName(_fromUtf8("actionSet_output_folder"))
        self.actionExecute_Scheme = QtGui.QAction(win_main)
        self.actionExecute_Scheme.setObjectName(_fromUtf8("actionExecute_Scheme"))
        self.actionLoad_Scheme = QtGui.QAction(win_main)
        self.actionLoad_Scheme.setObjectName(_fromUtf8("actionLoad_Scheme"))
        self.actionSave_Scheme = QtGui.QAction(win_main)
        self.actionSave_Scheme.setObjectName(_fromUtf8("actionSave_Scheme"))
        self.actionSet_Default = QtGui.QAction(win_main)
        self.actionSet_Default.setObjectName(_fromUtf8("actionSet_Default"))
        self.actionExit = QtGui.QAction(win_main)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionNew_Scheme = QtGui.QAction(win_main)
        self.actionNew_Scheme.setObjectName(_fromUtf8("actionNew_Scheme"))
        self.actionLicensing = QtGui.QAction(win_main)
        self.actionLicensing.setObjectName(_fromUtf8("actionLicensing"))
        self.actionUpdate_License = QtGui.QAction(win_main)
        self.actionUpdate_License.setObjectName(_fromUtf8("actionUpdate_License"))
        self.actionDebug = QtGui.QAction(win_main)
        self.actionDebug.setObjectName(_fromUtf8("actionDebug"))
        self.actionBug = QtGui.QAction(win_main)
        self.actionBug.setObjectName(_fromUtf8("actionBug"))
        self.menuFile.addAction(self.actionLoad_Scheme)
        self.menuFile.addAction(self.actionSave_Scheme)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAdvanced.addAction(self.actionLog_Settings)
        self.menuAdvanced.addAction(self.actionLog_to_file)
        self.menuAdvanced.addSeparator()
        self.menuAdvanced.addAction(self.actionEdit_Scheme)
        self.menuAdvanced.addSeparator()
        self.menuAdvanced.addAction(self.actionGenerate_Command)
        self.menuAdvanced.addSeparator()
        self.menuAdvanced.addAction(self.actionDebug)
        self.menuAdvanced.addAction(self.actionBug)
        self.menuHelp.addAction(self.actionExportFormat)
        self.menuHelp.addAction(self.actionDocumentation_2)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionLicensing)
        self.menuHelp.addAction(self.actionUpdate_License)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuVIEW.addAction(self.actionSet_raw_txt_path)
        self.menuVIEW.addAction(self.actionSet_data_npy_path)
        self.menuVIEW.addAction(self.actionSet_output_folder)
        self.menuVIEW.addSeparator()
        self.menuVIEW.addAction(self.actionExecute_Scheme)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuVIEW.menuAction())
        self.menubar.addAction(self.menuAdvanced.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(win_main)
        self.stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(win_main)

    def retranslateUi(self, win_main):
        win_main.setWindowTitle(QtGui.QApplication.translate("win_main", "Telem-A-Gator", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTitle.setText(QtGui.QApplication.translate("win_main", " ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMenuData.setToolTip(QtGui.QApplication.translate("win_main", "Data Path Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMenuExperiment.setToolTip(QtGui.QApplication.translate("win_main", "Experimental Design", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMenuOutput.setToolTip(QtGui.QApplication.translate("win_main", "Data Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setHtml(QtGui.QApplication.translate("win_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\" bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:32px; font-weight:600;\">Telem-A-Gator<br /></span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px; font-style:italic;\">by Scott W Harden</span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px;\"><br /><br /></span></p>\n"
"<table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\">\n"
"<tr>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New,courier\'; font-size:14px;\">Licenced to:</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New,courier\'; font-size:14px;\">Eric G Krause</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New,courier\'; font-size:14px;\">License Type:</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New,courier\'; font-size:14px;\">unlimited</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New,courier\'; font-size:14px;\">Key:</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New,courier\'; font-size:14px;\">7d9ey-qf76f-24f2a-64v5c</span></p></td></tr></table>\n"
"<p style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:x-large; font-weight:600; text-decoration: underline;\">Change Log</span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px;\"> </span></p>\n"
"<p style=\" margin-top:8px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px; font-weight:600;\">2013-05-14</span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:30px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px;\">- baseline/experiment dates are recalculated when \'display data summary\' is pressed <br /><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px; font-weight:600;\">2013-05-02</span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:30px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px;\">- modified image and excel output to automatically save scheme in same folder <br /><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px; font-weight:600;\">2013-05-01</span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:30px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px;\">- corrected normalization error bars so stdev=(stdev^2+stdev^2)^.5 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:30px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px;\">- prevented multiple launch windows from opening after image export </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:30px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px;\">- enabled HTML export </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:8px; margin-left:30px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px;\">- created summary view button </span></p>\n"
"<p style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:x-large; font-weight:600; text-decoration: underline;\">Suggested Features</span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px;\"> </span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" fo.npy files should have header information describing units, start/stop time, etc. so this information doesn\'t have to be stored in the file name. <br /><br /></li>\n"
"<li style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" fosweeps should be displayed starting at 19:00 (whatever the start time was) rather than 0:00. <br /><br /></li>\n"
"<li style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12px;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" foExcel output time format should be 12:00:00 and 12:06:00 rather than 12.00 and 12.10 <br /><br /></li></ul></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("win_main", "START HERE", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit.setPlainText(QtGui.QApplication.translate("win_main", "To begin analysis of new telemetry data, first export the data from the telemetry software as a series of TXT files into a single folder. For more information on how to do this, click \"Help\" and select \"Telemetry Export Format\".\n"
"\n"
"To analyze telemetry data, TXT files must be converted into NPY files which the Telem-A-Gator is designed to read. To convert a folder of TXT files to a folder of NPY files, use the form below.\n"
"\n"
"Once conversion is complete, analysis can begin.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("win_main", "Telemetry Export data folder (location of .txt files that will be read)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetRaw.setText(QtGui.QApplication.translate("win_main", "Set Path", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInputLine1.setText(QtGui.QApplication.translate("win_main", "contains 12 .txt files", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInputLine2.setText(QtGui.QApplication.translate("win_main", "most recent update: 2012/06/01 05:23:43 T6.txt", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("win_main", "Telem-A-Gator data folder (location where .npy files will be saved)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetLocation.setText(QtGui.QApplication.translate("win_main", "Set Path", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOutputLine1.setText(QtGui.QApplication.translate("win_main", "contains 312 .npy files (12 animals, 6 features)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOutputLine2.setText(QtGui.QApplication.translate("win_main", "most recent update: 2012/06/01 05:23:43 T6-Systolic-something.npy", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOutputLine3.setText(QtGui.QApplication.translate("win_main", "No unconverted data detected", None, QtGui.QApplication.UnicodeUTF8))
        self.grpConvert.setTitle(QtGui.QApplication.translate("win_main", "File Conversion", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConvert.setText(QtGui.QApplication.translate("win_main", "CONVERT", None, QtGui.QApplication.UnicodeUTF8))
        self.progConvertAnimal.setFormat(QtGui.QApplication.translate("win_main", "%v/%m (%p%)", None, QtGui.QApplication.UnicodeUTF8))
        self.progConvertFeature.setFormat(QtGui.QApplication.translate("win_main", "%v/%m (%p%)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblConvertFeature.setText(QtGui.QApplication.translate("win_main", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.lblConvertAnimal.setText(QtGui.QApplication.translate("win_main", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("win_main", "Animals:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("win_main", "Features:", None, QtGui.QApplication.UnicodeUTF8))
        self.listAnimals.setSortingEnabled(True)
        self.listFeatures.setSortingEnabled(True)
        self.label_28.setText(QtGui.QApplication.translate("win_main", "Data Start:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLastData.setText(QtGui.QApplication.translate("win_main", "2012/01/01 00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFirstData.setText(QtGui.QApplication.translate("win_main", "2012/01/01 00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("win_main", "Data End:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("win_main", "Constraints", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("win_main", "Bin:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkSweeps.setText(QtGui.QApplication.translate("win_main", "24 Hour Sweeps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("win_main", "statistics:", None, QtGui.QApplication.UnicodeUTF8))
        self.grpBaseline.setTitle(QtGui.QApplication.translate("win_main", "Baseline", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("win_main", "End: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("win_main", "Start: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("win_main", "YYYY/MM/DD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("win_main", "HH:MM:SS", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetTime4.setToolTip(QtGui.QApplication.translate("win_main", "set to last data point", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetTime3.setToolTip(QtGui.QApplication.translate("win_main", "set to first data point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("win_main", "Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("win_main", "Experiment", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("win_main", "End: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("win_main", "Start: ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetTime1.setToolTip(QtGui.QApplication.translate("win_main", "set to first data point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("win_main", "HH:MM:SS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("win_main", "YYYY/MM/DD", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetTime2.setToolTip(QtGui.QApplication.translate("win_main", "set to last data point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("win_main", "Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSummary.setText(QtGui.QApplication.translate("win_main", "Display Data Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("win_main", "Scheme Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExecute.setToolTip(QtGui.QApplication.translate("win_main", "take all the scheme information and execute it, performing analysis, statistics, etc.", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExecute.setText(QtGui.QApplication.translate("win_main", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.progExecute.setFormat(QtGui.QApplication.translate("win_main", "%v/%m (%p%)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStatus.setText(QtGui.QApplication.translate("win_main", "waiting for execution", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("win_main", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPlotBaseline.setText(QtGui.QApplication.translate("win_main", "Baseline", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPlotExperiment.setText(QtGui.QApplication.translate("win_main", "Experiment", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPlotNormalized.setText(QtGui.QApplication.translate("win_main", "Delta", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("win_main", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPrimary.setText(QtGui.QApplication.translate("win_main", "Average Trace", None, QtGui.QApplication.UnicodeUTF8))
        self.chkSecondary.setText(QtGui.QApplication.translate("win_main", "Individual Traces", None, QtGui.QApplication.UnicodeUTF8))
        self.chkErr.setText(QtGui.QApplication.translate("win_main", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.grpOutput.setTitle(QtGui.QApplication.translate("win_main", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("win_main", "Folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetOutputFolder.setText(QtGui.QApplication.translate("win_main", "Set Path", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOutputOpen.setText(QtGui.QApplication.translate("win_main", "Open Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExcel.setToolTip(QtGui.QApplication.translate("win_main", "save an excel document (.CSV) to the output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExcel.setText(QtGui.QApplication.translate("win_main", "Save as Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.btnImages.setToolTip(QtGui.QApplication.translate("win_main", "save a series of images to the output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.btnImages.setText(QtGui.QApplication.translate("win_main", "Save as Images", None, QtGui.QApplication.UnicodeUTF8))
        self.btnHTML.setToolTip(QtGui.QApplication.translate("win_main", "save a HTML summary to the output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.btnHTML.setText(QtGui.QApplication.translate("win_main", "Save as HTML", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSaveScheme.setToolTip(QtGui.QApplication.translate("win_main", "create a copy of this scheme and place it in the output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSaveScheme.setText(QtGui.QApplication.translate("win_main", "Save Scheme", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("win_main", "Feature:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLaunchInteractive.setToolTip(QtGui.QApplication.translate("win_main", "display the graph below in a large, interactive window", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLaunchInteractive.setText(QtGui.QApplication.translate("win_main", "launch interactive", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setHtml(QtGui.QApplication.translate("win_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">This version of </span><span style=\" font-size:12pt; font-weight:600;\">Telem-A-Gator</span><span style=\" font-size:12pt;\"> is for testing purposes only.</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">This version of </span><span style=\" font-size:12pt; font-weight:600;\">Telem-A-Gator</span><span style=\" font-size:12pt;\"> is not to be copied, modified, or distributed, without the express written consent of the CJF Laboratory at the University of Florida in Gainesville, Florida.  This software may be protected by the University of Florida Office of Technology Licensing.</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Written by:</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Scott W Harden</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">http://www.SWHarden.com</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">SWHarden@gmail.com</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Clarles J Frazier</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">http://www.cop.ufl.edu/2010/09/charlesjason-frazier</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">frazier@cop.ufl.edu</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("win_main", "Register To:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("win_main", "Software Key:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("win_main", "Hardware ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("win_main", "USING THE TELEMETRY SOFTWARE, EXPORT DATA EXACTLY LIKE THIS:", None, QtGui.QApplication.UnicodeUTF8))
        self.textDebug.setPlainText(QtGui.QApplication.translate("win_main", "DEBUG LOG:\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDebug.setText(QtGui.QApplication.translate("win_main", "debug", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("win_main", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAdvanced.setTitle(QtGui.QApplication.translate("win_main", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("win_main", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuVIEW.setTitle(QtGui.QApplication.translate("win_main", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScheme_Editor.setText(QtGui.QApplication.translate("win_main", "IO paths", None, QtGui.QApplication.UnicodeUTF8))
        self.actionData_Analysis.setText(QtGui.QApplication.translate("win_main", "Data Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDebug_Log.setText(QtGui.QApplication.translate("win_main", "Debug Log", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_Scheme.setText(QtGui.QApplication.translate("win_main", "Edit Scheme", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_Command.setText(QtGui.QApplication.translate("win_main", "Generate CMD", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPop_up_Log.setText(QtGui.QApplication.translate("win_main", "Pop-up Log", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLog_Settings.setText(QtGui.QApplication.translate("win_main", "Log Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLog_to_file.setText(QtGui.QApplication.translate("win_main", "Log to file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportFormat.setText(QtGui.QApplication.translate("win_main", "Telemetry Export Format", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation_2.setText(QtGui.QApplication.translate("win_main", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("win_main", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_raw_txt_path.setText(QtGui.QApplication.translate("win_main", "Set raw (.txt) path", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_data_npy_path.setText(QtGui.QApplication.translate("win_main", "Set data (.npy) path", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_output_folder.setText(QtGui.QApplication.translate("win_main", "Set output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExecute_Scheme.setText(QtGui.QApplication.translate("win_main", "Execute Scheme", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Scheme.setText(QtGui.QApplication.translate("win_main", "Load Scheme", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Scheme.setText(QtGui.QApplication.translate("win_main", "Save Scheme", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Default.setText(QtGui.QApplication.translate("win_main", "Set Default", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("win_main", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Scheme.setText(QtGui.QApplication.translate("win_main", "New Scheme", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLicensing.setText(QtGui.QApplication.translate("win_main", "View License", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate_License.setText(QtGui.QApplication.translate("win_main", "Update License", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDebug.setText(QtGui.QApplication.translate("win_main", "Debug Window", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBug.setText(QtGui.QApplication.translate("win_main", "Create Bug Report", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    win_main = QtGui.QMainWindow()
    ui = Ui_win_main()
    ui.setupUi(win_main)
    win_main.show()
    sys.exit(app.exec_())

